export const SPECIALTIES: Record<string, string[]> = {
  "Restauração": [
    "Restaurante",
    "Café / Pastelaria",
    "Snack Bar / Fast Food",
    "Take-away / Delivery",
    "Marisqueira / Churrasqueira",
    "Bar / Pub",
    "Catering",
    "Outros",
  ],
  "Retalho Alimentar": [
    "Supermercado / Mercearia",
    "Talho",
    "Peixaria",
    "Padaria / Confeitaria",
    "Frutaria",
    "Adega / Garrafeira",
    "Outros",
  ],
  "Saúde": [
    "Clínica Dentária",
    "Clínica Médica",
    "Medicina Estética",
    "Farmácia",
    "Fisioterapia",
    "Psicologia",
    "Nutrição",
    "Outros",
  ],
  "Beleza": [
    "Cabeleireiro",
    "Barbearia",
    "Centro de Estética",
    "Spa / Massagens",
    "Manicure / Pedicure",
    "Outros",
  ],
  "Desporto e Fitness": [
    "Ginásio / Fitness",
    "Yoga / Pilates",
    "Artes Marciais",
    "Natação / Piscina",
    "Personal Trainer",
    "Outros",
  ],
  "Tecnologia": [
    "Desenvolvimento de Software",
    "Informática / Reparação",
    "Marketing Digital",
    "E-commerce",
    "Consultoria IT",
    "Outros",
  ],
  "Moda e Calçado": [
    "Loja de Roupa",
    "Sapataria",
    "Acessórios / Joalharia",
    "Moda Infantil",
    "Moda Desportiva",
    "Outros",
  ],
  "Construção e Reparações": [
    "Construção Civil",
    "Remodelações / Obras",
    "Eletricidade",
    "Canalizações",
    "Pintura",
    "Serralharia / Carpintaria",
    "Arquitetura / Design de Interiores",
    "Outros",
  ],
  "Automóvel": [
    "Oficina / Mecânica",
    "Concessionário",
    "Lavagem / Detailing",
    "Pneus / Jantes",
    "Carroçaria",
    "Eletricidade Auto",
    "Outros",
  ],
  "Jurídico e Financeiro": [
    "Advogado / Solicitador",
    "Contabilidade / Fiscalidade",
    "Seguros",
    "Mediação Imobiliária",
    "Consultoria Financeira",
    "Outros",
  ],
  "Educação": [
    "Escola / Colégio",
    "Centro de Explicações",
    "Escola de Línguas",
    "Formação Profissional",
    "Escola de Condução",
    "Creche / Jardim de Infância",
    "Outros",
  ],
  "Turismo e Alojamento": [
    "Hotel / Hostel",
    "Alojamento Local",
    "Agência de Viagens",
    "Rent-a-Car",
    "Animação Turística",
    "Outros",
  ],
  "Animais e Veterinária": [
    "Clínica Veterinária",
    "Pet Shop",
    "Grooming / Banho e Tosa",
    "Hotel para Animais",
    "Outros",
  ],
  "Serviços Profissionais": [
    "Limpeza",
    "Segurança / Vigilância",
    "Logística / Transportes",
    "Comunicação / Publicidade",
    "Fotografia / Vídeo",
    "Jardinagem / Paisagismo",
    "Eventos / Organização",
    "Outros",
  ],
  "Outros": [
    "Outros",
  ],
};
